name: app_chat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # logic
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  auto_route: ^8.0.3

  # ui
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.8.0
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.17

  # firebase



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
